"""fix typo

Revision ID: 164dfea374cf
Revises: 7b4a7f14c27d
Create Date: 2026-02-21 00:05:05.813766

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '164dfea374cf'
down_revision: Union[str, Sequence[str], None] = '7b4a7f14c27d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('parent_id', sa.Integer(), nullable=True))
    op.drop_constraint(op.f('departments_parend_id_fkey'), 'departments', type_='foreignkey')
    op.create_foreign_key(None, 'departments', 'departments', ['parent_id'], ['id'])
    op.drop_column('departments', 'parend_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('departments', sa.Column('parend_id', sa.INTEGER(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'departments', type_='foreignkey')
    op.create_foreign_key(op.f('departments_parend_id_fkey'), 'departments', 'departments', ['parend_id'], ['id'])
    op.drop_column('departments', 'parent_id')
    # ### end Alembic commands ###
