"""add unique constraint

Revision ID: f49ddc3d4c54
Revises: 164dfea374cf
Create Date: 2026-02-23 00:05:08.587290

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f49ddc3d4c54'
down_revision: Union[str, Sequence[str], None] = '164dfea374cf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint('name_parent_id_unique', 'departments', ['name', 'parent_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('name_parent_id_unique', 'departments', type_='unique')
    # ### end Alembic commands ###
